//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Temperature
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public int MeasuringId { get; set; }
        public short Value { get; set; }
    
        internal virtual City City { get; set; }
        internal virtual Measuring Measuring { get; set; }
    }
}
