//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherDBEntities : DbContext
    {
        public WeatherDBEntities()
            : base("name=WeatherDBEntities")
        {
            Cities = Set<City>();
            Descriptions = Set<Description>();
            Measurings = Set<Measuring>();
            Temperatures = Set<Temperature>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<City> Cities { get; set; }
        internal virtual DbSet<Description> Descriptions { get; set; }
        internal virtual DbSet<Measuring> Measurings { get; set; }
        internal virtual DbSet<Temperature> Temperatures { get; set; }
    }
}
